#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

 exec-once = ~/.config/waybar/scripts/launch.sh
 exec-once = swww-daemon
 exec-once = swaync
 exec-once = wl-paste --type text --watch cliphist store # Stores only text data
 exec-once = wl-paste --type image --watch cliphist store # Stores only image data

 exec-once = wl-clip-persist --clipboard regular
 exec-once = hypridle
